import { InnovationType, InnovationNature, InnovationLocus, InnovationItem } from '../types/innovation';

export const INNOVATION_TYPES: readonly InnovationType[] = [
  'Design & Marketing',
  'Product',
  'Service',
  'Market & Customer Channel',
  'Technology',
  'Process',
  'Management',
  'Business Model',
  'Industry',
] as const;

export const INNOVATION_NATURES: readonly InnovationNature[] = [
  'Sustaining',
  'Efficiency',
  'Disruptive',
] as const;

export const INNOVATION_LOCI: readonly InnovationLocus[] = [
  'Small Teams',
  'Projects',
  'Organisations',
  'Business Ecosystem',
] as const;

// Color schemes
export const NATURE_COLORS: Record<InnovationNature, { hex: string; threeHex: number; label: string; bgClass: string; textClass: string }> = {
  Sustaining: {
    hex: '#38bdf8', // sky-400
    threeHex: 0x38bdf8,
    label: 'Sustaining',
    bgClass: 'bg-sky-500/10 text-sky-400 border border-sky-500/30',
    textClass: 'text-sky-400',
  },
  Efficiency: {
    hex: '#34d399', // emerald-400
    threeHex: 0x34d399,
    label: 'Efficiency',
    bgClass: 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/30',
    textClass: 'text-emerald-400',
  },
  Disruptive: {
    hex: '#f59e0b', // amber-500
    threeHex: 0xf59e0b,
    label: 'Disruptive',
    bgClass: 'bg-amber-500/10 text-amber-400 border border-amber-500/30',
    textClass: 'text-amber-400',
  },
};

export const TYPE_COLORS: Record<InnovationType, { hex: string; threeHex: number; shortLabel: string }> = {
  'Design & Marketing': { hex: '#f43f5e', threeHex: 0xf43f5e, shortLabel: 'Design & Mkt' },
  'Product': { hex: '#ec4899', threeHex: 0xec4899, shortLabel: 'Product' },
  'Service': { hex: '#d946ef', threeHex: 0xd946ef, shortLabel: 'Service' },
  'Market & Customer Channel': { hex: '#8b5cf6', threeHex: 0x8b5cf6, shortLabel: 'Channel' },
  'Technology': { hex: '#3b82f6', threeHex: 0x3b82f6, shortLabel: 'Technology' },
  'Process': { hex: '#06b6d4', threeHex: 0x06b6d4, shortLabel: 'Process' },
  'Management': { hex: '#10b981', threeHex: 0x10b981, shortLabel: 'Management' },
  'Business Model': { hex: '#f59e0b', threeHex: 0xf59e0b, shortLabel: 'Biz Model' },
  'Industry': { hex: '#f97316', threeHex: 0xf97316, shortLabel: 'Industry' },
};

export const LOCUS_DETAILS: Record<InnovationLocus, { shortLabel: string; description: string }> = {
  'Small Teams': {
    shortLabel: 'Teams',
    description: 'Rapid iterations, agile squads, skunkworks, internal tiger teams',
  },
  'Projects': {
    shortLabel: 'Projects',
    description: 'Structured cross-functional initiatives, capital projects, dedicated programs',
  },
  'Organisations': {
    shortLabel: 'Organisations',
    description: 'Company-wide operating models, cultural shifts, institutional overhauls',
  },
  'Business Ecosystem': {
    shortLabel: 'Ecosystem',
    description: 'Supply chains, platform partners, open standards, industry consortia',
  },
};

// Initial preset innovations for testing and demonstration - Single Company Portfolio: Apple Inc.
export const INITIAL_PRESET_INNOVATIONS: InnovationItem[] = [
  {
    id: 'demo-1',
    companyName: 'Apple Inc.',
    innovationName: 'iPhone Multi-Touch UI & App Store',
    description: 'Capacitive touch interface paired with global app distribution platform transforming mobile computing.',
    type: 'Product',
    nature: 'Disruptive',
    locus: 'Business Ecosystem',
    year: 2007,
    createdAt: Date.now() - 1000000,
  },
  {
    id: 'demo-2',
    companyName: 'Apple Inc.',
    innovationName: 'Apple Silicon M-Series Unified Architecture',
    description: 'System-on-Chip design unifying CPU, GPU, and Neural Engine on unified high-bandwidth memory.',
    type: 'Technology',
    nature: 'Disruptive',
    locus: 'Small Teams',
    year: 2020,
    createdAt: Date.now() - 900000,
  },
  {
    id: 'demo-3',
    companyName: 'Apple Inc.',
    innovationName: 'Apple Retail Stores & Genius Bar Service',
    description: 'Architectural experience hubs with walk-up hardware troubleshooting and personal setup sessions.',
    type: 'Market & Customer Channel',
    nature: 'Disruptive',
    locus: 'Organisations',
    year: 2001,
    createdAt: Date.now() - 800000,
  },
  {
    id: 'demo-4',
    companyName: 'Apple Inc.',
    innovationName: 'Kaizen JIT Global Supply Chain Logistics',
    description: 'Precision manufacturing synchronization and supplier direct fulfillment eliminating inventory holding.',
    type: 'Process',
    nature: 'Sustaining',
    locus: 'Small Teams',
    year: 1998,
    createdAt: Date.now() - 700000,
  },
  {
    id: 'demo-5',
    companyName: 'Apple Inc.',
    innovationName: 'Swift Programming Language & Xcode Toolchain',
    description: 'Modern type-safe open-source systems language and LLDB debugger streamlining iOS development.',
    type: 'Technology',
    nature: 'Disruptive',
    locus: 'Business Ecosystem',
    year: 2014,
    createdAt: Date.now() - 600000,
  },
  {
    id: 'demo-6',
    companyName: 'Apple Inc.',
    innovationName: 'Apple Watch Continuous ECG & Heart Health Monitor',
    description: 'FDA-cleared wrist photoplethysmography sensor detecting atrial fibrillation and fall impact.',
    type: 'Product',
    nature: 'Sustaining',
    locus: 'Small Teams',
    year: 2018,
    createdAt: Date.now() - 500000,
  },
  {
    id: 'demo-7',
    companyName: 'Apple Inc.',
    innovationName: 'Apple Pay Tokenized Secure Enclave Payments',
    description: 'Biometric contactless EMV payment system tokenizing credentials to eliminate physical card fraud.',
    type: 'Service',
    nature: 'Disruptive',
    locus: 'Business Ecosystem',
    year: 2014,
    createdAt: Date.now() - 400000,
  },
  {
    id: 'demo-8',
    companyName: 'Apple Inc.',
    innovationName: 'DRI (Directly Responsible Individual) Accountability Framework',
    description: 'Explicit operational governance assigning a single accountable engineer to every deliverable.',
    type: 'Management',
    nature: 'Sustaining',
    locus: 'Organisations',
    year: 1997,
    createdAt: Date.now() - 300000,
  },
  {
    id: 'demo-9',
    companyName: 'Apple Inc.',
    innovationName: 'Closed-Loop Aluminum & Daisy Disassembly Robotics',
    description: 'Automated reverse-logistics robot disassembling 200 iPhones/hr to reclaim rare earth elements.',
    type: 'Process',
    nature: 'Efficiency',
    locus: 'Organisations',
    year: 2018,
    createdAt: Date.now() - 200000,
  },
  {
    id: 'demo-10',
    companyName: 'Apple Inc.',
    innovationName: 'Dynamic Island Adaptive Sensory UI',
    description: 'Interactive morphing pill UI seamlessly integrating physical camera pill with live app activities.',
    type: 'Design & Marketing',
    nature: 'Efficiency',
    locus: 'Projects',
    year: 2022,
    createdAt: Date.now() - 100000,
  },
  {
    id: 'demo-11',
    companyName: 'Apple Inc.',
    innovationName: 'AppleCare+ Express Replacement Subscription',
    description: 'End-to-end device protection with advance hardware dispatch and automated diagnostics.',
    type: 'Service',
    nature: 'Efficiency',
    locus: 'Organisations',
    year: 2011,
    createdAt: Date.now() - 50000,
  },
  {
    id: 'demo-12',
    companyName: 'Apple Inc.',
    innovationName: 'Human Interface Guidelines (HIG) Spatial Standard',
    description: 'Universal interaction design specification standardizing typography, touch targets, and haptics.',
    type: 'Design & Marketing',
    nature: 'Sustaining',
    locus: 'Business Ecosystem',
    year: 1984,
    createdAt: Date.now() - 10000,
  },
  {
    id: 'demo-13',
    companyName: 'Apple Inc.',
    innovationName: 'Apple One Integrated Services Bundle',
    description: 'Single recurring subscription tying storage, music, TV, fitness, and arcade into unified billing.',
    type: 'Business Model',
    nature: 'Disruptive',
    locus: 'Business Ecosystem',
    year: 2020,
    createdAt: Date.now() - 9000,
  },
  {
    id: 'demo-14',
    companyName: 'Apple Inc.',
    innovationName: 'AirPods Spatial Audio with Dynamic Head Tracking',
    description: 'Directional audio filters and micro-gyroscope frequency calibration creating virtual surround sound.',
    type: 'Product',
    nature: 'Disruptive',
    locus: 'Projects',
    year: 2020,
    createdAt: Date.now() - 8000,
  },
  {
    id: 'demo-15',
    companyName: 'Apple Inc.',
    innovationName: 'Clean Energy Supplier Decarbonization Consortia',
    description: 'Mandating and financing 100% renewable electricity transition across 250+ Tier-1 manufacturing partners.',
    type: 'Industry',
    nature: 'Disruptive',
    locus: 'Business Ecosystem',
    year: 2015,
    createdAt: Date.now() - 7000,
  },
  {
    id: 'demo-16',
    companyName: 'Apple Inc.',
    innovationName: 'iPhone Annual Upgrade Direct-Financing Program',
    description: 'Zero-percent installment hardware subscription with built-in annual trade-in upgrade cycle.',
    type: 'Business Model',
    nature: 'Disruptive',
    locus: 'Organisations',
    year: 2015,
    createdAt: Date.now() - 6000,
  },
  {
    id: 'demo-17',
    companyName: 'Apple Inc.',
    innovationName: 'Private Cloud Compute Confidential Silicon Architecture',
    description: 'Server-side LLM inference executed strictly inside custom Apple Silicon enclaves with verified wiping.',
    type: 'Technology',
    nature: 'Disruptive',
    locus: 'Projects',
    year: 2024,
    createdAt: Date.now() - 5000,
  },
  {
    id: 'demo-18',
    companyName: 'Apple Inc.',
    innovationName: 'Special Projects Skunkworks Prototyping Group',
    description: 'Autonomous multi-disciplinary incubator teams exploring autonomous robotics and advanced optics.',
    type: 'Management',
    nature: 'Disruptive',
    locus: 'Projects',
    year: 2014,
    createdAt: Date.now() - 4000,
  },
];
